Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Max: 50

Style/GuardClause:
  Enabled: false