default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST_DEVELOPMENT'] %>
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000

development:
  <<: *default
  database: iot_development

test:
  <<: *default
  database: iot_test

production:
  <<: *default
  database: iot_production
  host: <%= ENV['DATABASE_HOST_PRODUCTION'] %>
